
# Field config configures the auto review functions that will apply to each class
# in a document's prediction

# FIELD_CONFIG:
#   Class 1:
#     - <----------- Please note this hyphen, it's important so this gets read a list
#       function: Function 1
#       kwargs: 
#       prediction_set: all
#     -     
#       function: Function 2
#       kwargs: 
#            kwarg1: asdf
#            kwarg2: asdfas
#       prediction_set: all

#   Class 2:
#     -
#       function: Function 3
#       kwargs: 
#           kwarg1: asdf
#           kwarg2: asdfd
#       prediction_set: all

# Note that the functions you apply need to have an appropriate mapping in
# the REVIEWERS dictionary in reviewer.py

FIELD_CONFIG:
  Check Amount:
    -
      function: split_merged_values
      kwargs: 
      prediction_set: all
  Check Date:
    -
      function: split_merged_values
      kwargs: 
      prediction_set: all
  Check Number:
    -
      function: split_merged_values
      kwargs: 
      prediction_set: all
  Deposit Amount:
    -
      function: split_merged_values
      kwargs: 
      prediction_set: all
  Deposit Date:
    -
      function: split_merged_values
      kwargs: 
      prediction_set: all
  Withdrawal Amount:
    -
      function: split_merged_values
      kwargs: 
      prediction_set: all
  Withdrawal Date:
    -
      function: split_merged_values
      kwargs: 
      prediction_set: all
  
    
    
